import Link from "next/link";
import { ArrowLeft, ClipboardList, ChevronRight } from "lucide-react";
import { Brand } from "@/components/brand";
import { EmptyState } from "@/components/empty-state";
import { LogoutButton } from "@/components/logout-button";
import { activityStateLabel, effectiveActivityState, formatSchoolDate } from "@/lib/activities";
import { requireStudent } from "@/lib/authorization";
import { prisma } from "@/lib/db";

const types:Record<string,string>={EXTERNAL_LINK:"Link externo",FORM:"Formulário",GROUP:"Em grupo"};
export default async function StudentActivities(){const{student}=await requireStudent();const[recipients,settings]=await Promise.all([prisma.activityRecipient.findMany({where:{studentId:student.id},include:{activity:true,submission:{select:{status:true}},award:{select:{awardedXp:true}}},orderBy:{createdAt:"desc"}}),prisma.appSetting.findUnique({where:{id:1},select:{timeZone:true}})]);const timeZone=settings?.timeZone??"America/Fortaleza";return <main className="mesh mobile-safe min-h-screen"><div className="mx-auto max-w-5xl px-4 sm:px-8"><header className="flex h-20 items-center justify-between border-b border-white/7"><Brand context="Estudante"/><LogoutButton/></header><Link href="/aluno" className="mt-6 inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Início</Link><p className="eyebrow mt-6">Minha turma</p><h1 className="mt-3 font-display text-3xl font-bold">Atividades</h1><p className="mt-2 text-sm text-slate-400">Acompanhe prazos, envios e correções.</p><div className="mt-6 space-y-4">{recipients.length?recipients.map(recipient=>{const state=effectiveActivityState(recipient.activity);const status=recipient.award?`Corrigida · ${recipient.award.awardedXp} XP`:recipient.submission?recipient.submission.status==="AWAITING_REVIEW"?"Aguardando correção":"Enviada":recipient.studentSignaledAt?"Realizada · aguardando professor":"Pendente";return <Link key={recipient.id} href={`/aluno/atividades/${recipient.activityId}`} className="glass focus-ring flex items-center gap-4 rounded-2xl p-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><ClipboardList size={20}/></span><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-blue-300">{types[recipient.activity.type]} · {activityStateLabel[state]}</p><h2 className="mt-1 truncate font-bold">{recipient.activity.title}</h2><p className="mt-1 text-xs text-slate-400">Até {formatSchoolDate(recipient.activity.closesAt,timeZone)} · {status}</p></div><ChevronRight className="shrink-0 text-slate-500" size={18}/></Link>}):<EmptyState icon={ClipboardList} title="Nenhuma atividade" description="Quando o professor publicar uma atividade para sua turma, ela aparecerá aqui."/>}</div></div></main>}
