import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, UsersRound } from "lucide-react";
import { ActivityStateActions, LinkGradeForm, TeamGradeForm } from "@/components/activity-teacher-actions";
import { ProfessorShell } from "@/components/professor-shell";
import { activityStateLabel, effectiveActivityState, formatSchoolDate } from "@/lib/activities";
import { prisma } from "@/lib/db";

const typeLabels:Record<string,string>={EXTERNAL_LINK:"Link externo",FORM:"Formulário",GROUP:"Em grupo"};
export default async function ActivityDetail({params}:{params:Promise<{id:string}>}){
  const{id}=await params;
  const[activity,settings]=await Promise.all([
    prisma.activity.findUnique({where:{id},include:{recipients:{include:{student:{select:{id:true,firstName:true,lastName:true,status:true,originSchoolClass:true}},submission:{select:{id:true,status:true,submittedAt:true}},award:true},orderBy:{student:{firstName:"asc"}}},teams:{include:{members:{include:{student:{select:{firstName:true,lastName:true}},recipient:{include:{award:true}}}}},orderBy:{position:"asc"}},questions:{orderBy:{position:"asc"}}}}),
    prisma.appSetting.findUnique({where:{id:1},select:{timeZone:true}}),
  ]);
  if(!activity)notFound();
  const state=effectiveActivityState(activity);const submitted=activity.recipients.filter(item=>item.submission);const awaiting=activity.recipients.filter(item=>item.submission?.status==="AWAITING_REVIEW");const completed=activity.recipients.filter(item=>item.award||item.studentSignaledAt);const pending=activity.recipients.filter(item=>!item.submission&&!item.studentSignaledAt&&!item.award);const timeZone=settings?.timeZone??"America/Fortaleza";
  return <ProfessorShell title="Detalhes da atividade">
    <Link href="/professor/atividades" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Voltar</Link>
    <section className="glass mt-6 rounded-3xl p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">{typeLabels[activity.type]} · Toda a turma de Robótica</p><h2 className="mt-3 font-display text-3xl font-bold">{activity.title}</h2>{activity.description&&<p className="mt-3 max-w-3xl whitespace-pre-wrap text-sm leading-relaxed text-slate-300">{activity.description}</p>}</div><span className="rounded-full bg-blue-400/10 px-4 py-2 text-sm font-bold text-blue-300">{activityStateLabel[state]}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-3"><Info label="Abertura" value={formatSchoolDate(activity.opensAt,timeZone)}/><Info label="Fechamento" value={formatSchoolDate(activity.closesAt,timeZone)}/><Info label="Pontuação máxima" value={`${activity.maxXp} XP`}/></dl><div className="mt-6 border-t border-slate-800 pt-5"><ActivityStateActions activityId={activity.id} state={state}/></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Summary icon={CheckCircle2} label={activity.type==="FORM"?"Enviaram":"Concluíram/avisaram"} value={activity.type==="FORM"?submitted.length:completed.length}/><Summary icon={Clock3} label="Aguardando correção" value={awaiting.length}/><Summary icon={UsersRound} label="Pendentes" value={pending.length}/></section>
    {activity.type==="EXTERNAL_LINK"&&<section className="mt-7"><h3 className="font-display text-xl font-bold">Acompanhamento individual</h3>{activity.externalUrl&&<a href={activity.externalUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-2 text-sm text-blue-300">Ver link externo <ExternalLink size={15}/></a>}<div className="mt-4 space-y-3">{activity.recipients.map(recipient=><article key={recipient.id} className="glass rounded-2xl p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{recipient.student.firstName} {recipient.student.lastName}</p><p className="text-xs text-slate-400">{recipient.studentSignaledAt?"Aluno marcou como realizada":"Sem aviso de realização"} · {recipient.award?`${recipient.award.awardedXp} XP concedido`:"Ainda não corrigida"}</p></div><LinkGradeForm activityId={activity.id} studentId={recipient.studentId} maxXp={activity.maxXp} currentXp={recipient.award?.awardedXp} currentObservation={recipient.award?.observation}/></article>)}</div></section>}
    {activity.type==="FORM"&&<section className="mt-7"><h3 className="font-display text-xl font-bold">Envios</h3><p className="mt-1 text-sm text-slate-400">Enviar não significa estar corrigido. Respostas escritas aguardam avaliação manual.</p><div className="mt-4 space-y-3">{activity.recipients.map(recipient=><article key={recipient.id} className="glass flex flex-wrap items-center justify-between gap-3 rounded-2xl p-4"><div><p className="font-bold">{recipient.student.firstName} {recipient.student.lastName}</p><p className="text-xs text-slate-400">{recipient.submission?recipient.submission.status==="GRADED"?`Corrigida · ${recipient.award?.awardedXp??0} XP`:"Enviada · aguardando correção":"Pendente"}</p></div>{recipient.submission&&<Link href={`/professor/atividades/${activity.id}/corrigir/${recipient.submission.id}`} className="button-secondary py-2">Ver respostas</Link>}</article>)}</div></section>}
    {activity.type==="GROUP"&&<section className="mt-7"><h3 className="font-display text-xl font-bold">Equipes da turma de Robótica</h3><p className="mt-1 text-sm text-slate-400">As equipes podem reunir alunos de diferentes turmas regulares. A pontuação é concedida individualmente; revisões aplicam somente a diferença.</p><div className="mt-4 grid gap-4 xl:grid-cols-2">{activity.teams.map(team=>{const firstAward=team.members.find(member=>member.recipient.award)?.recipient.award;return <article key={team.id} className="glass rounded-2xl p-5"><div className="flex justify-between gap-3"><h4 className="font-bold">{team.name}</h4><span className="text-xs text-slate-400">{team.completedAt?"Concluída":"Pendente"}</span></div><ul className="mt-3 space-y-1 text-sm text-slate-300">{team.members.map(member=><li key={member.id}>{member.student.firstName} {member.student.lastName} · {member.recipient.award?.awardedXp??"—"} XP</li>)}</ul><TeamGradeForm activityId={activity.id} teamId={team.id} maxXp={activity.maxXp} currentXp={firstAward?.awardedXp}/></article>})}</div></section>}
  </ProfessorShell>;
}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
function Summary({icon:Icon,label,value}:{icon:typeof CheckCircle2;label:string;value:number}){return <div className="glass rounded-2xl p-4"><Icon className="text-blue-300" size={19}/><p className="mt-3 text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>}
