/* This file is generated from src/content/sticker-catalog/*.json. */
import type { StickerCatalogEntry } from "@/lib/asset-catalog-files";
export const STICKER_CATALOG: readonly StickerCatalogEntry[] = [
  {
    "slug": "rhanna-choft",
    "number": 1,
    "name": "Rhanna Choft",
    "description": "Dominando a arte secular da dobradura de vento, Rhanna é uma mestra de artes marciais lendária, respeitada e temida nas arenas por sua precisão avassaladora. Seus leques de combate deslizam pelo ar criando lâminas de vento e tufões instantâneos. Porém, por trás da postura rígida de guerreira imbatível, Rhanna é extremamente afável, acolhedora e fã de chás quentes — um contraste que pega de surpresa qualquer um que sobreviva aos seus treinos.",
    "alt": "Personagem Fictício",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/rhanna-choft.webp",
    "totalCopies": 60,
    "rarity": "HIGH",
    "score": 50,
    "state": "DRAFT",
    "sha256": "ee684bfdfb790862604f492e1a6bcfbf911c07de1c6c6cf56568da76ac14dfdb",
    "width": 900,
    "height": 1200,
    "bytes": 105580,
    "preparedAt": "2026-09-28T23:34:13.465Z"
  },
  {
    "slug": "zek-vangogue",
    "number": 2,
    "name": "Zek Vangogue",
    "description": "Prodigioso e imprevisível, Zek possui uma conexão nata com a energia mística do cosmos, conseguindo dobrar a matéria astral e moldar galáxias em miniatura. O grande problema? Sua coordenação motora não acompanha seu poder surreal. Zek vive tropeçando nas próprias vestes, derrubando pergaminhos preciosos e acidentalmente invocando pequenas tempestades estelares. Apesar do jeito avoado, seu coração puro e determinação o tornam um aliado valioso — e imprevisível — em batalha.",
    "alt": "Personagem Fictício",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/zek-vangogue.webp",
    "totalCopies": 50,
    "rarity": "HIGH",
    "score": 60,
    "state": "DRAFT",
    "sha256": "0957761470d52b5062481571714a5c826a7bc100f74bc9cbe7b34aefa1a69b7c",
    "width": 900,
    "height": 1200,
    "bytes": 114880,
    "preparedAt": "2026-09-28T23:35:42.085Z"
  },
  {
    "slug": "kael-kaelen",
    "number": 3,
    "name": "Os Gêmeos Kalvin (Kael e Kaelen)",
    "description": "Nascidos sob a mesma lua sombria, os gêmeos não atendem por conceitos morais como \"bem\" ou \"mal\"; eles guiam-se por suas próprias regras e pelo peso de suas armas. Kael, o mais velho por minutos, ostenta uma postura imponente e carrega uma espada maciça imbuída de runas elétricas. Kaelen, mais reservado e sorrateiro, esconde o rosto sob um capuz e empunha nunchakus que rasgam a realidade com energia gravitacional. Conhecidos por aceitar apenas missões que testem seus limites, os dois formam uma",
    "alt": "Personagem Fictício",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/kael-kaelen.webp",
    "totalCopies": 45,
    "rarity": "HIGH",
    "score": 67,
    "state": "DRAFT",
    "sha256": "c99c43351172dca1ac87677cff4ac72b114628cdcbba4dc426465c5375d6ae28",
    "width": 900,
    "height": 1200,
    "bytes": 137188,
    "preparedAt": "2026-09-28T23:37:17.095Z"
  },
  {
    "slug": "emilly-keora",
    "number": 4,
    "name": "Emilly Keora",
    "description": "Estudiosa das artes arcanas e astrológicas, Emilly Keora é uma maga enigmática e decidida que carrega o cosmos no topo de sua cabeça. Seu marcante e imponente chapeu pontudo — decorado com bússolas celestes, pingentes de estrela e runas de constelações — funciona como um focalizador para seus feitiços astrais. Mestra em manipular orbes de energia mística e poeira estelar, Emilly combina sabedoria antiga com uma aura misteriosa. Sempre equipada com poções fluindo e pergaminhos raros em sua bolsa",
    "alt": "Personagem",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/emilly-keora.webp",
    "totalCopies": 60,
    "rarity": "HIGH",
    "score": 50,
    "state": "DRAFT",
    "sha256": "af5e0b183787a2bf34bae5eacd2e477f2e78ed2868fa6c86c54731b6f399f857",
    "width": 900,
    "height": 1200,
    "bytes": 128494,
    "preparedAt": "2026-09-28T23:47:50.669Z"
  },
  {
    "slug": "turma-do-barulho",
    "number": 5,
    "name": "A Turma do Barulho",
    "description": "Liderados pelo sagaz goblin encapuzado, este grupo caótico de criaturinhas verdes e pontudas semeia confusão por onde passa[cite: 5]. Com suas poções caseiras, bombas instáveis e truques mágicos imprevisíveis, a Turma do Barulho é uma força da natureza desajeitada e hilária, pronta para transformar qualquer aventura numa verdadeira explosão de gargalhadas — e de tudo o que estiver por perto",
    "alt": "Personagem Fictício",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/turma-do-barulho.webp",
    "totalCopies": 100,
    "rarity": "HIGH",
    "score": 30,
    "state": "DRAFT",
    "sha256": "16af24f95e1911d5b8b158935a5eb8440126e09b6c6901cea81a9ee3e58ed40d",
    "width": 900,
    "height": 1200,
    "bytes": 166958,
    "preparedAt": "2026-09-29T00:03:31.831Z"
  },
  {
    "slug": "g-blues",
    "number": 6,
    "name": "G-Blues",
    "description": "Esta trupe caótica de goblins azuis, com suas feições pontudas e expressões maníacas, parece ter transformado um antigo altar de pedra em um laboratório de alquimia improvisado e perigoso",
    "alt": "img",
    "collectionSlug": "the-bogues",
    "collectionName": "The Borgues",
    "imagePath": "/media/stickers/the-bogues/g-blues.webp",
    "totalCopies": 500,
    "rarity": "LOW",
    "score": 6,
    "state": "DRAFT",
    "sha256": "b2f6d0258d93f830997231924297a9bc1cc5b476f7977681fe8782174192d0ee",
    "width": 900,
    "height": 1200,
    "bytes": 177134,
    "preparedAt": "2026-09-29T00:19:28.860Z"
  }
];
