"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ActivityStateActions({activityId,state}:{activityId:string;state:string}){const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function act(action:"CLOSE"|"REOPEN",closesAt?:string){setBusy(true);setError("");const response=await fetch(`/api/professor/activities/${activityId}/state`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...(closesAt?{closesAt}:{})})});const data=await response.json();if(!response.ok)setError(data.message);else router.refresh();setBusy(false)}return <div className="flex flex-wrap items-end gap-3">{state!=="CLOSED"?<button disabled={busy} onClick={()=>act("CLOSE")} className="button-secondary">Fechar agora</button>:<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);act("REOPEN",String(form.get("closesAt")))}} className="flex flex-wrap items-end gap-2"><label className="text-xs text-slate-400">Novo fechamento no fuso da escola<input required name="closesAt" type="datetime-local" className="input mt-1 py-2"/></label><button disabled={busy} className="button-primary py-2">Reabrir</button></form>}{error&&<p className="w-full text-sm text-rose-300">{error}</p>}</div>}

export function LinkGradeForm({activityId,studentId,maxXp,currentXp,currentObservation}:{activityId:string;studentId:string;maxXp:number;currentXp?:number;currentObservation?:string|null}){const router=useRouter();const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch(`/api/professor/activities/${activityId}/grade-link`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,awardedXp:Number(form.get("xp")),observation:form.get("observation")})});const data=await response.json();setMessage(response.ok?"Correção salva.":data.message);if(response.ok)router.refresh()}return <form onSubmit={submit} className="mt-3 grid gap-2 sm:grid-cols-[110px_1fr_auto]"><input aria-label="XP atribuído" required name="xp" type="number" min="0" max={maxXp} defaultValue={currentXp??0} className="input py-2"/><input aria-label="Observação" name="observation" defaultValue={currentObservation??""} placeholder="Observação da correção" className="input py-2"/><button className="button-secondary py-2">{currentXp===undefined?"Corrigir":"Revisar"}</button>{message&&<span className="text-xs text-slate-400 sm:col-span-3">{message}</span>}</form>}

export function TeamGradeForm({activityId,teamId,maxXp,currentXp}:{activityId:string;teamId:string;maxXp:number;currentXp?:number}){const router=useRouter();const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch(`/api/professor/activities/${activityId}/teams/${teamId}/grade`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({awardedXp:Number(form.get("xp")),observation:form.get("observation")})});const data=await response.json();setMessage(response.ok?"Pontuação aplicada individualmente a todos os integrantes.":data.message);if(response.ok)router.refresh()}return <form onSubmit={submit} className="mt-4 grid gap-2 sm:grid-cols-[110px_1fr_auto]"><input aria-label="XP por integrante" required name="xp" type="number" min="0" max={maxXp} defaultValue={currentXp??0} className="input py-2"/><input aria-label="Observação" name="observation" placeholder="Observação para a equipe" className="input py-2"/><button className="button-secondary py-2">{currentXp===undefined?"Confirmar equipe":"Revisar nota"}</button>{message&&<span className="text-xs text-slate-400 sm:col-span-3">{message}</span>}</form>}
