"use client";
import { useState } from "react";
import { BookOpen, CheckCircle2, Copy, LockKeyhole, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";

type Student={id:string;firstName:string;lastName:string;originSchoolClass:string|null};
type Lesson={id:string;title:string;openedAt:string;attendances:{studentId:string;status:string}[]};

export function LessonControl({initialLesson,initialStudents}:{initialLesson:Lesson|null;initialStudents:Student[]}){
  const router=useRouter();const[lesson,setLesson]=useState(initialLesson);const[students,setStudents]=useState(initialStudents);const[modal,setModal]=useState<"open"|"close"|null>(null);const[code,setCode]=useState<string|null>(null);const[excused,setExcused]=useState<string[]>([]);const[busy,setBusy]=useState(false);
  async function reload(){const response=await fetch("/api/professor/lessons");const data=await response.json();setLesson(data.lesson);setStudents(data.students)}
  async function open(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const response=await fetch("/api/professor/lessons",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title")})});const data=await response.json();setBusy(false);if(!response.ok){toast.error(data.message);return}setCode(data.code);await reload();setModal(null);toast.success("Aula aberta para toda a turma de Robótica.");router.refresh()}
  async function close(){if(!lesson)return;setBusy(true);const response=await fetch(`/api/professor/lessons/${lesson.id}/close`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({excusedIds:excused})});const data=await response.json();setBusy(false);if(!response.ok){toast.error(data.message);return}setLesson(null);setStudents([]);setCode(null);setModal(null);toast.success(`Aula fechada para ${data.students} aluno(s). XP aplicado.`);router.refresh()}
  const present=new Set(lesson?.attendances.filter(attendance=>attendance.status==="PRESENT").map(attendance=>attendance.studentId));
  return <><div className="mt-7 flex flex-wrap gap-3">{!lesson?<button onClick={()=>setModal("open")} className="button-primary"><Plus size={17}/>Abrir nova aula</button>:<div className="flex w-full flex-col gap-4 rounded-2xl border border-emerald-400/25 bg-emerald-400/8 p-5 sm:flex-row sm:items-center"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-400/15 text-emerald-300"><BookOpen/></span><div className="flex-1"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Aula aberta · toda a turma</p><h3 className="font-display font-bold">{lesson.title}</h3><p className="text-xs text-slate-400">{lesson.attendances.length} presença(s) de {students.length} participante(s)</p></div>{code&&<button onClick={()=>{navigator.clipboard.writeText(code);toast.success("Código copiado.")}} className="button-secondary font-mono text-lg"><Copy size={16}/>{code}</button>}<button onClick={()=>setModal("close")} className="button-primary"><LockKeyhole size={16}/>Revisar e fechar</button></div>}</div>
    {modal&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/85 p-4"><div className="glass my-6 w-full max-w-xl rounded-2xl p-6"><div className="flex justify-between"><h3 className="font-display text-xl font-bold">{modal==="open"?"Abrir nova aula":"Revisar fechamento"}</h3><button onClick={()=>setModal(null)} aria-label="Fechar"><X/></button></div>{modal==="open"?<form onSubmit={open} className="mt-6 space-y-4"><input name="title" className="input" placeholder="Título da aula" required/><p className="rounded-xl border border-blue-400/20 bg-blue-400/8 p-3 text-sm text-blue-100">A aula incluirá todos os alunos ativos da turma de Robótica, independentemente da turma regular de origem.</p><button disabled={busy} className="button-primary w-full">Abrir aula e gerar código</button></form>:<div className="mt-6"><p className="text-sm text-slate-400">Presentes receberão +30 XP. Marque como justificada cada ausência aplicável (+10 XP); as demais receberão −50 XP.</p><div className="mt-4 max-h-80 space-y-2 overflow-y-auto">{students.map(student=>{const isPresent=present.has(student.id);return <label key={student.id} className="flex items-center gap-3 rounded-xl border border-slate-700 p-3"><span className={`h-2.5 w-2.5 rounded-full ${isPresent?"bg-emerald-400":"bg-rose-400"}`}/><span className="flex-1 text-sm">{student.firstName} {student.lastName}</span>{isPresent?<span className="text-xs text-emerald-300">Presente</span>:<span className="flex items-center gap-2 text-xs text-amber-200"><input type="checkbox" checked={excused.includes(student.id)} onChange={event=>setExcused(current=>event.target.checked?[...current,student.id]:current.filter(id=>id!==student.id))}/>Falta justificada</span>}</label>})}</div><button disabled={busy} onClick={close} className="button-primary mt-5 w-full"><CheckCircle2 size={17}/>{busy?"Fechando...":"Confirmar fechamento e aplicar XP"}</button></div>}</div></div>}
  </>;
}
