"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bot, Copy, DoorOpen, Gamepad2, LoaderCircle, LogOut, Pause, Play, Radio, RefreshCw, Send, Share2, ShieldAlert, Trophy, UserPlus, Users, Wifi, WifiOff, XCircle } from "lucide-react";
import { LUDO_CHAT_MESSAGES, type LudoChatKey } from "@/lib/ludo-chat";
import { globalTrackSquare, parsePieces, validPieceIndexesForPlayer } from "@/lib/ludo-rules";

type Player = { id: string; studentId: string | null; kind: "STUDENT" | "BOT"; name: string; profileAvatar: string; color: "RED" | "GREEN" | "YELLOW" | "BLUE"; seat: number; status: string; pieces: unknown; stake: number; payout: number; finishPosition: number | null; connected: boolean; disconnectedAt: string | null };
type Room = { id: string; code: string; ownerId: string; ownerName: string; mode: "HUMAN" | "BOT"; status: string; wager: number; roomFee: number; maxPlayers: number; initialPlayerCount: number | null; currentSeat: number; currentRoll: number | null; pauseRequestCount: number; turnDeadline: string | null; startedAt: string | null; pausedAt: string | null; finishedAt: string | null; createdAt: string; version: number; viewer: { xp: number; devCoins: number } | null; players: Player[]; moves: Array<{ id: string; playerId: string; sequence: number; kind: string; roll: number | null; pieceIndex: number | null; autoReason: string | null; createdAt: string }> };
type OnlineStudent = { id: string; firstName: string; lastName: string; profileAvatar: string };
type Chat = { id: string; sender: string; text: string };

const colorClass = { RED: "bg-red-500 border-red-200", GREEN: "bg-emerald-500 border-emerald-200", YELLOW: "bg-yellow-400 border-yellow-100", BLUE: "bg-blue-500 border-blue-200" };
const colorSoft = { RED: "bg-red-500/15 text-red-200 border-red-400/25", GREEN: "bg-emerald-500/15 text-emerald-200 border-emerald-400/25", YELLOW: "bg-yellow-400/15 text-yellow-100 border-yellow-300/25", BLUE: "bg-blue-500/15 text-blue-200 border-blue-400/25" };

export function LudoRoomClient({ initialRoom, viewerId }: { initialRoom: Room; viewerId: string }) {
  const [room, setRoom] = useState(initialRoom);
  const [online, setOnline] = useState<OnlineStudent[]>([]);
  const [chat, setChat] = useState<Chat[]>([]);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [now, setNow] = useState(0);
  const [realtime, setRealtime] = useState(false);
  const socketRef = useRef<WebSocket | null>(null);
  const ticking = useRef(false);

  const refresh = useCallback(async () => {
    const response = await fetch(`/api/student/minigames/ludo/rooms/${room.id}`, { cache: "no-store" });
    const data = await response.json(); if (response.ok) setRoom(data.room);
  }, [room.id]);

  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(timer); }, []);
  useEffect(() => {
    let closed = false; let retry: ReturnType<typeof setTimeout> | null = null; let fallback: ReturnType<typeof setInterval> | null = null;
    const connect = () => {
      const protocol = location.protocol === "https:" ? "wss:" : "ws:";
      const socket = new WebSocket(`${protocol}//${location.host}/api/student/minigames/ludo/ws`); socketRef.current = socket;
      socket.addEventListener("open", () => setRealtime(true));
      socket.addEventListener("message", event => { try { const message = JSON.parse(event.data); if (message.type === "ready") socket.send(JSON.stringify({ type: "subscribe-room", roomId: room.id })); if (message.type === "room" && message.roomId === room.id) void refresh(); if (message.type === "chat" && message.roomId === room.id) { const item = { id: crypto.randomUUID(), sender: message.payload.sender, text: message.payload.text }; setChat(current => [...current.slice(-5), item]); setTimeout(() => setChat(current => current.filter(value => value.id !== item.id)), 12_000); } } catch { /* ignora */ } });
      socket.addEventListener("close", () => { setRealtime(false); if (!closed) retry = setTimeout(connect, 2_000); });
    };
    connect(); fallback = setInterval(() => { if (!socketRef.current || socketRef.current.readyState !== WebSocket.OPEN) void refresh(); }, 5_000);
    return () => { closed = true; if (retry) clearTimeout(retry); if (fallback) clearInterval(fallback); socketRef.current?.close(); };
  }, [refresh, room.id]);

  useEffect(() => {
    if (room.status !== "WAITING" || room.ownerId !== viewerId || room.mode !== "HUMAN") return;
    const load = async () => { const response = await fetch("/api/student/minigames/ludo/presence", { cache: "no-store" }); const data = await response.json(); if (response.ok) setOnline(data.students.filter((item: OnlineStudent) => !room.players.some(player => player.studentId === item.id))); };
    void load(); const timer = setInterval(load, 15_000); return () => clearInterval(timer);
  }, [room.mode, room.ownerId, room.players, room.status, viewerId]);

  const seconds = room.turnDeadline ? (now ? Math.max(0, Math.ceil((new Date(room.turnDeadline).getTime() - now) / 1000)) : 10) : 0;
  useEffect(() => {
    if (room.status !== "ACTIVE" || !room.turnDeadline || seconds > 0 || ticking.current) return;
    ticking.current = true;
    fetch(`/api/student/minigames/ludo/rooms/${room.id}/tick`, { method: "POST" }).then(response => response.json().then(data => ({ response, data }))).then(({ response, data }) => { if (response.ok) setRoom(data.room); }).finally(() => { ticking.current = false; });
  }, [room.id, room.status, room.turnDeadline, seconds]);

  async function action(name: string, body?: unknown) {
    setBusy(name); setError("");
    try { const response = await fetch(`/api/student/minigames/ludo/rooms/${room.id}/${name}`, { method: "POST", headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.message); if (data.room) setRoom(data.room); return data; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível realizar a ação."); return null; }
    finally { setBusy(""); }
  }
  async function copy(value: string, label: string) { await navigator.clipboard.writeText(value); alert(`${label} copiado.`); }
  async function invite(studentId: string) { const result = await action("invite", { inviteeId: studentId }); if (result) alert(result.chargedXp ? `Convite enviado. Foram descontados ${result.chargedXp} XP pelo novo pacote de cinco convites.` : `Convite enviado. Restam ${result.remainingInBatch} neste pacote.`); }
  function sendChat(key: LudoChatKey) { if (socketRef.current?.readyState === WebSocket.OPEN) socketRef.current.send(JSON.stringify({ type: "chat", roomId: room.id, key })); }

  const me = room.players.find(player => player.studentId === viewerId);
  const current = room.players.find(player => player.seat === room.currentSeat);
  const myTurn = room.status === "ACTIVE" && current?.studentId === viewerId && me?.status === "PLAYING";
  const valid = myTurn && room.currentRoll !== null && me ? validPieceIndexesForPlayer(room.players.map(player => ({ id: player.id, color: player.color, pieces: parsePieces(player.pieces) })), me.id, room.currentRoll) : [];
  const owner = room.ownerId === viewerId;
  return <main className="mesh mobile-safe min-h-screen"><div className="mx-auto max-w-7xl px-4 pb-24 sm:px-8">
    <header className="flex min-h-20 flex-wrap items-center justify-between gap-3 border-b border-white/7 py-3"><Link href="/aluno/minigames/ludo" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/15 text-cyan-200"><Gamepad2/></span><span><span className="eyebrow">Ludo Maker</span><strong className="block font-mono text-lg">{room.code}</strong></span></Link><div className="flex items-center gap-2"><span className={`flex items-center gap-1 rounded-full px-3 py-2 text-xs ${realtime ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-200"}`}>{realtime ? <Wifi size={14}/> : <WifiOff size={14}/>} {realtime ? "Tempo real" : "Reconectando"}</span><Status value={room.status}/></div></header>
    {error && <p role="alert" className="mt-4 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</p>}
    <section className="mt-5 grid gap-5 xl:grid-cols-[280px_minmax(420px,1fr)_300px]">
      <aside className="space-y-5"><RoomInfo room={room} seconds={seconds} copy={copy}/><PlayerList room={room} currentPlayerId={current?.id}/>{room.status === "WAITING" && owner && room.mode === "HUMAN" && <InvitePanel students={online} busy={busy === "invite"} invite={invite}/>}</aside>
      <section className="min-w-0"><LudoBoard room={room} viewerId={viewerId} valid={valid} onPiece={pieceIndex => void action("move", { pieceIndex })}/><TurnControl room={room} current={current} owner={owner} myTurn={myTurn} valid={valid} seconds={seconds} busy={busy} action={action}/></section>
      <aside className="space-y-5"><RulesPanel room={room}/><ChatPanel messages={chat} send={sendChat}/><Actions room={room} owner={owner} busy={busy} action={action}/></aside>
    </section>
  </div></main>;
}

function RoomInfo({ room, seconds, copy }: { room: Room; seconds: number; copy: (value: string, label: string) => void }) { return <section className="glass rounded-2xl p-4"><p className="eyebrow">Sala de montagem</p><div className="mt-2 flex items-center justify-between"><strong className="font-mono text-2xl tracking-widest text-cyan-200">{room.code}</strong><button onClick={() => copy(room.code, "Código")} className="focus-ring rounded-lg p-2 hover:bg-white/5" aria-label="Copiar código"><Copy size={17}/></button></div><button onClick={() => copy(`${location.origin}/aluno/minigames/ludo?codigo=${room.code}`, "Link")} className="button-secondary mt-3 w-full text-xs"><Share2 size={15}/>Copiar link da partida</button><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><Info label="Aposta" value={`${room.wager} DC`}/><Info label="Jogadores" value={`${room.players.length}/${room.maxPlayers}`}/><Info label="Dono" value={room.ownerName}/><Info label="Relógio" value={room.status === "ACTIVE" ? `${seconds}s` : "—"}/></dl></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-white/[.035] p-2"><dt className="text-[10px] text-slate-500">{label}</dt><dd className="mt-1 truncate font-semibold">{value}</dd></div>; }
function PlayerList({ room, currentPlayerId }: { room: Room; currentPlayerId?: string }) { return <section className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 font-display font-bold"><Users size={18}/>Robôs na pista</h2><div className="mt-3 space-y-2">{room.players.map(player => <div key={player.id} className={`rounded-xl border p-3 ${colorSoft[player.color]} ${currentPlayerId === player.id ? "ring-2 ring-white/50" : ""}`}><div className="flex items-center gap-2">{player.kind === "BOT" ? <Bot size={18}/> : <span className={`h-3 w-3 rounded-full ${player.connected ? "bg-emerald-300" : "bg-slate-600"}`}/>}<strong className="min-w-0 flex-1 truncate text-sm">{player.name}</strong>{player.finishPosition && <span className="font-bold">{player.finishPosition}º</span>}</div><div className="mt-2 flex justify-between text-[10px]"><span>{player.status === "FORFEITED" ? "Desistiu" : player.connected ? "Online" : "Desconectado"}</span><span>{player.payout > 0 ? `Prêmio: ${player.payout} DC` : `Aposta: ${player.stake} DC`}</span></div></div>)}</div></section>; }
function InvitePanel({ students, busy, invite }: { students: OnlineStudent[]; busy: boolean; invite: (id: string) => void }) { return <section className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 font-display font-bold"><Radio className="text-emerald-300" size={18}/>Alunos online</h2><p className="mt-2 text-[11px] text-slate-500">Cada pacote de cinco convites para a mesma pessoa custa 10 XP.</p><div className="mt-3 max-h-64 space-y-2 overflow-auto">{students.length ? students.map(student => <button disabled={busy} onClick={() => invite(student.id)} key={student.id} className="flex w-full items-center gap-2 rounded-lg bg-white/[.035] p-3 text-left text-sm hover:bg-white/[.07]"><span className="h-2 w-2 rounded-full bg-emerald-300"/><span className="min-w-0 flex-1 truncate">{student.firstName} {student.lastName}</span><UserPlus size={15}/></button>) : <p className="py-4 text-center text-xs text-slate-500">Nenhum colega online agora.</p>}</div></section>; }

const TRACK: Array<[number, number]> = [[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const HOME: Record<Player["color"], Array<[number, number]>> = { RED: [[7,1],[7,2],[7,3],[7,4],[7,5],[7,6]], GREEN: [[1,7],[2,7],[3,7],[4,7],[5,7],[6,7]], YELLOW: [[7,13],[7,12],[7,11],[7,10],[7,9],[7,8]], BLUE: [[13,7],[12,7],[11,7],[10,7],[9,7],[8,7]] };
function LudoBoard({ room, viewerId, valid, onPiece }: { room: Room; viewerId: string; valid: number[]; onPiece: (index: number) => void }) {
  const tokens = useMemo(() => { const map = new Map<string, Array<{ player: Player; pieceIndex: number }>>(); for (const player of room.players) parsePieces(player.pieces).forEach((position, pieceIndex) => { let coord: [number, number] | undefined; if (position >= 0 && position <= 51) coord = TRACK[globalTrackSquare(player.color, position) ?? 0]; else if (position >= 52) coord = HOME[player.color][position - 52]; if (coord) { const key = `${coord[0]}-${coord[1]}`; map.set(key, [...(map.get(key) ?? []), { player, pieceIndex }]); } }); return map; }, [room.players]);
  return <section className="relative mx-auto aspect-square w-full max-w-[720px] overflow-hidden rounded-3xl border-4 border-slate-700 bg-slate-950 p-2 shadow-2xl shadow-cyan-950/30"><div className="grid h-full w-full grid-cols-[repeat(15,minmax(0,1fr))] grid-rows-[repeat(15,minmax(0,1fr))] overflow-hidden rounded-2xl bg-slate-900">{Array.from({ length: 225 }, (_, index) => { const row = Math.floor(index / 15), col = index % 15, key = `${row}-${col}`; const trackIndex = TRACK.findIndex(([r,c]) => r === row && c === col); const homeColor = (Object.keys(HOME) as Player["color"][]).find(color => HOME[color].some(([r,c]) => r === row && c === col)); const quadrant = row < 6 && col < 6 ? "RED" : row < 6 && col > 8 ? "GREEN" : row > 8 && col > 8 ? "YELLOW" : row > 8 && col < 6 ? "BLUE" : null; const center = row >= 6 && row <= 8 && col >= 6 && col <= 8; const cellTokens = tokens.get(key) ?? []; return <div key={key} className={`relative grid place-items-center border border-slate-700/50 ${center ? "bg-gradient-to-br from-red-500 via-yellow-400 to-blue-500" : homeColor ? colorClass[homeColor].split(" ")[0] : trackIndex >= 0 ? "bg-slate-100" : quadrant ? colorClass[quadrant].split(" ")[0] + " opacity-80" : "bg-slate-900"}`}>{trackIndex >= 0 && [0,8,13,21,26,34,39,47].includes(trackIndex) && <span className="text-[8px] text-slate-600">★</span>}{cellTokens.map(({ player, pieceIndex }, tokenIndex) => { const canMove = player.studentId === viewerId && valid.includes(pieceIndex); return <button key={`${player.id}-${pieceIndex}`} disabled={!canMove} onClick={() => onPiece(pieceIndex)} aria-label={`Mover robô ${pieceIndex + 1} de ${player.name}`} className={`absolute h-[62%] w-[62%] rounded-full border-2 shadow-md ${colorClass[player.color]} ${canMove ? "z-20 animate-pulse cursor-pointer ring-2 ring-white" : "z-10"}`} style={{ transform: `translate(${(tokenIndex % 2) * 35 - 18}%, ${Math.floor(tokenIndex / 2) * 35 - 18}%)` }}/>} )}</div>; })}</div><BaseTokens room={room} viewerId={viewerId} valid={valid} onPiece={onPiece}/></section>;
}
function BaseTokens({ room, viewerId, valid, onPiece }: { room: Room; viewerId: string; valid: number[]; onPiece: (index: number) => void }) { const placements: Record<Player["color"], string> = { RED: "left-[8%] top-[8%]", GREEN: "right-[8%] top-[8%]", YELLOW: "bottom-[8%] right-[8%]", BLUE: "bottom-[8%] left-[8%]" }; return <>{room.players.map(player => { const base = parsePieces(player.pieces).map((position, index) => ({ position, index })).filter(item => item.position === -1); if (!base.length) return null; return <div key={player.id} className={`pointer-events-none absolute grid w-[20%] grid-cols-2 gap-2 rounded-2xl bg-slate-950/70 p-2 ${placements[player.color]}`}>{base.map(item => { const canMove = player.studentId === viewerId && valid.includes(item.index); return <button key={item.index} disabled={!canMove} onClick={() => onPiece(item.index)} className={`pointer-events-auto aspect-square rounded-full border-2 ${colorClass[player.color]} ${canMove ? "animate-pulse ring-2 ring-white" : ""}`} aria-label={`Retirar robô ${item.index + 1} da oficina`}/>; })}</div>; })}</>; }

function TurnControl({ room, current, owner, myTurn, valid, seconds, busy, action }: { room: Room; current?: Player; owner: boolean; myTurn: boolean; valid: number[]; seconds: number; busy: string; action: (name: string, body?: unknown) => Promise<unknown> }) { if (room.status === "WAITING") return <section className="glass mx-auto mt-5 max-w-[720px] rounded-2xl p-5 text-center"><h2 className="font-display text-xl font-bold">Aguardando a equipe</h2><p className="mt-2 text-sm text-slate-400">O dono pode iniciar quando houver pelo menos dois jogadores. Depois disso ninguém mais entra.</p>{owner && <button disabled={room.players.length < 2 || Boolean(busy)} onClick={() => action("start")} className="button-primary mt-4"><Play size={17}/>Iniciar partida · custa 100 XP</button>}</section>;
  if (room.status === "PAUSED") return <section className="glass mx-auto mt-5 max-w-[720px] rounded-2xl p-5 text-center"><Pause className="mx-auto text-amber-300"/><h2 className="mt-3 font-display text-xl font-bold">Circuito pausado</h2><p className="mt-2 text-sm text-slate-400">O estado está salvo. O dono pode continuar quando os participantes estiverem prontos.</p></section>;
  if (room.status === "FINISHED") return <section className="glass mx-auto mt-5 max-w-[720px] rounded-2xl p-5 text-center"><Trophy className="mx-auto text-yellow-300"/><h2 className="mt-3 font-display text-2xl font-bold">Missão concluída!</h2><p className="mt-2 text-sm text-slate-300">Confira as posições e os prêmios nos cartões dos jogadores.</p></section>;
  if (room.status !== "ACTIVE") return null;
  const progress = Math.max(0, Math.min(1, seconds / 10));
  return <section className={`glass mx-auto mt-5 max-w-[720px] rounded-2xl p-5 ${myTurn ? "ring-2 ring-cyan-400/50" : ""}`}><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><p className="eyebrow">{myTurn ? "Sua vez" : "Aguardando"}</p><h2 className="mt-1 font-display text-xl font-bold">{current?.name ?? "—"}</h2><p className="mt-1 text-xs text-slate-400">{room.currentRoll ? `Número sorteado: ${room.currentRoll}${valid.length ? " · escolha um robô" : ""}` : "Aguardando sorteio de 1 a 6"}</p></div><div className="relative grid h-20 w-20 place-items-center rounded-full" style={{ background: `conic-gradient(#22d3ee ${progress * 360}deg, rgba(51,65,85,.5) 0)` }}><div className="grid h-16 w-16 place-items-center rounded-full bg-[#111d2f]"><strong className="text-2xl">{seconds}</strong></div></div><button disabled={!myTurn || room.currentRoll !== null || Boolean(busy)} onClick={() => action("roll")} className="button-primary min-w-44">{busy === "roll" ? <LoaderCircle className="animate-spin" size={18}/> : <RefreshCw size={18}/>}Sortear número</button></div></section>; }

function RulesPanel({ room }: { room: Room }) { return <section className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 font-display font-bold"><ShieldAlert size={18}/>Regras desta sala</h2><ul className="mt-3 space-y-2 text-xs leading-relaxed text-slate-300"><li>• Taxa já paga: <strong>50 DC</strong>.</li><li>• Aposta por participante: <strong>{room.wager} DC</strong>.</li><li>• Quatro robôs; só saem da oficina com número 6.</li><li>• Dez segundos para sortear e dez para escolher.</li><li>• Desistência ou último lugar: <strong>-100 XP</strong>; podem acumular.</li><li>• 3 minutos desconectado: desistência automática.</li>{room.mode === "BOT" && <li className="text-fuchsia-200">• Há mais chances da IA do professor ganhar.</li>}</ul></section>; }
function ChatPanel({ messages, send }: { messages: Chat[]; send: (key: LudoChatKey) => void }) { return <section className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 font-display font-bold"><Send size={18}/>Chat rápido</h2><p className="mt-2 text-[10px] text-slate-500">Mensagens não são salvas no banco.</p><div aria-live="polite" className="mt-3 min-h-20 space-y-2">{messages.map(message => <p key={message.id} className="rounded-lg bg-white/5 p-2 text-xs"><strong>{message.sender}:</strong> {message.text}</p>)}</div><div className="mt-3 grid grid-cols-2 gap-2">{(Object.entries(LUDO_CHAT_MESSAGES) as [LudoChatKey,string][]).map(([key,text]) => <button key={key} onClick={() => send(key)} className="rounded-lg border border-slate-700 p-2 text-left text-[11px] hover:bg-white/5">{text}</button>)}</div></section>; }
function Actions({ room, owner, busy, action }: { room: Room; owner: boolean; busy: string; action: (name: string, body?: unknown) => Promise<unknown> }) { return <section className="glass rounded-2xl p-4"><h2 className="font-display font-bold">Controles</h2><div className="mt-3 grid gap-2">{room.status === "WAITING" && <button disabled={Boolean(busy)} className="button-secondary" onClick={() => { if (confirm(owner ? "Cancelar a sala? A taxa de 50 DC não será devolvida; as apostas serão." : "Sair da sala? Sua aposta será devolvida.")) void action(owner ? "cancel" : "leave"); }}>{owner ? <XCircle size={16}/> : <DoorOpen size={16}/>} {owner ? "Cancelar sala" : "Sair da sala"}</button>}{room.status === "ACTIVE" && <><button disabled={Boolean(busy)} className="button-secondary" onClick={() => action("pause")}><Pause size={16}/>{owner ? "Continuar mais tarde" : room.initialPlayerCount === 2 ? `Pedir pausa (${room.pauseRequestCount}/3)` : "Pedir para pausar"}</button><button disabled={Boolean(busy)} className="rounded-xl border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-sm font-bold text-rose-200" onClick={() => { if (confirm("Desistir desconta 100 XP adicionais e a aposta permanece no pote. Confirmar?")) void action("forfeit"); }}><LogOut className="inline" size={16}/> Desistir</button></>}{room.status === "PAUSED" && owner && <button disabled={Boolean(busy)} className="button-primary" onClick={() => action("resume")}><Play size={16}/>Continuar partida</button>}</div></section>; }
function Status({ value }: { value: string }) { const labels: Record<string,string> = { WAITING: "Aguardando", ACTIVE: "Em jogo", PAUSED: "Pausada", FINISHED: "Finalizada", CANCELLED: "Cancelada" }; return <span className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold">{labels[value] ?? value}</span>; }
