"use client";
import Image from "next/image";
import { useState } from "react";
import { CheckCircle2, Rocket } from "lucide-react";
import { toast } from "sonner";

type Item={slug:string;number:number;name:string;description:string;alt:string;collectionSlug:string;collectionName:string;imagePath:string;totalCopies:number;rarity:"LOW"|"MEDIUM"|"HIGH";score:number;sha256:string};

export function StickerCatalogManager({items,activeSlugs}:{items:readonly Item[];activeSlugs:string[]}){
  const[selected,setSelected]=useState<Item>();
  const[busy,setBusy]=useState(false);
  async function activate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);setBusy(true);try{const response=await fetch("/api/professor/stickers/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug:selected.slug,teacherPassword:form.get("teacherPassword"),expectedTotalCopies:selected.totalCopies,expectedRarity:selected.rarity,expectedScore:selected.score,confirmed:true})});const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success(data.created?"Figurinha e estoque ativados.":"Figurinha já estava ativa.");location.reload()}catch(error){toast.error(error instanceof Error?error.message:"Falha na ativação.")}finally{setBusy(false)}}
  return <div>
    <p className="mb-6 rounded-xl border border-blue-400/20 bg-blue-400/8 p-4 text-sm text-blue-100">Esta tela não faz upload. Ela ativa apenas manifestos que já chegaram a este deploy e cujo asset responde antes da transação.</p>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.map(item=>{const active=activeSlugs.includes(item.slug);return <article key={item.slug} className="glass overflow-hidden rounded-2xl"><div className="relative aspect-[3/4]"><Image src={item.imagePath} alt={item.alt} fill className="object-cover"/></div><div className="p-4"><p className="text-xs text-slate-500">#{item.number} · {item.collectionName}</p><h2 className="font-bold">{item.name}</h2><p className="mt-1 text-xs text-slate-400">{item.totalCopies} cópias · {item.rarity} · {item.score} pts</p><p className="mt-1 text-[10px] text-slate-600">asset {item.sha256.slice(0,12)}</p>{active?<p className="mt-4 flex items-center gap-2 text-sm font-bold text-emerald-300"><CheckCircle2 size={17}/>Ativa no banco</p>:<button className="button-primary mt-4 w-full" onClick={()=>setSelected(item)}><Rocket size={17}/>Ativar</button>}</div></article>})}</div>
    {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4" onMouseDown={event=>event.target===event.currentTarget&&!busy&&setSelected(undefined)}><form onSubmit={activate} role="dialog" aria-modal="true" aria-labelledby="activation-title" className="glass w-full max-w-md rounded-2xl p-6"><h2 id="activation-title" className="font-display text-xl font-bold">Ativar {selected.name}</h2><dl className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><dt className="text-slate-500">Cópias</dt><dd className="font-bold">{selected.totalCopies}</dd></div><div><dt className="text-slate-500">Raridade</dt><dd className="font-bold">{selected.rarity}</dd></div><div><dt className="text-slate-500">Score</dt><dd className="font-bold">{selected.score}</dd></div></dl><p className="mt-4 text-sm text-amber-200">A ativação cria o estoque no banco de produção. Depois da primeira distribuição, os dados de escassez ficam bloqueados.</p><label className="mt-4 block text-sm">Sua senha pessoal<input autoFocus className="input mt-2" name="teacherPassword" type="password" autoComplete="current-password" required/></label><div className="mt-5 flex gap-3"><button className="button-primary flex-1" disabled={busy}>{busy?"Ativando…":"Confirmar ativação"}</button><button className="button-secondary" type="button" disabled={busy} onClick={()=>setSelected(undefined)}>Cancelar</button></div></form></div>}
  </div>
}
