"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { Gift, PackageOpen, Search, ShoppingCart, Sparkles, Tag, X } from "lucide-react";
import { toast } from "sonner";

type Sticker = { id:string; slug:string; number:number; name:string; description:string; alt:string; imagePath:string; totalCopies:number; rarity:"LOW"|"MEDIUM"|"HIGH"; score:number; collection:{name:string;slug:string}; copies:{id:string;state:"OWNED"|"ESCROW"|"TREASURY"}[] };
type Listing = { id:string;price:number;expiresAt:string|Date;seller:{firstName:string};copy:{sticker:Omit<Sticker,"copies">} };
type Donation = {id:string;expiresAt:string|Date;sender:{firstName:string};copy:{sticker:{name:string;imagePath:string;alt:string}}};
type OwnListing = {id:string;price:number;expiresAt:string|Date;copy:{sticker:{name:string}}};
type PackSticker = Pick<Sticker,"slug"|"name"|"imagePath"|"rarity"|"score">;

const rarityLabels={LOW:"Baixa",MEDIUM:"Média",HIGH:"Alta"};

export function StickerAlbum({stickers,listings,ownListings,donations,devCoins,remainingPacks,treasuryStock,patent,score,marketEnabled}:{stickers:Sticker[];listings:Listing[];ownListings:OwnListing[];donations:Donation[];devCoins:number;remainingPacks:number;treasuryStock:Record<string,number>;patent:string;score:number;marketEnabled:boolean}){
  const[query,setQuery]=useState("");const[rarity,setRarity]=useState("ALL");const[busy,setBusy]=useState(false);
  const[marketOpen,setMarketOpen]=useState(marketEnabled);
  const[action,setAction]=useState<{kind:"SELL"|"DONATE";copyId:string;rarity?:Sticker["rarity"]}|null>(null);
  const[selectedSticker,setSelectedSticker]=useState<Sticker|null>(null);
  const[packReveal,setPackReveal]=useState<PackSticker[]|null>(null);
  const filtered=useMemo(()=>stickers.filter(s=>(rarity==="ALL"||s.rarity===rarity)&&s.name.toLowerCase().includes(query.toLowerCase())),[stickers,query,rarity]);
  const refreshMarket=useCallback(async()=>{try{const response=await fetch("/api/student/stickers/market",{cache:"no-store"});if(!response.ok)return;const data=await response.json();setMarketOpen(Boolean(data.enabled))}catch{}},[]);
  useEffect(()=>{const interval=window.setInterval(()=>void refreshMarket(),30_000);const onFocus=()=>void refreshMarket();window.addEventListener("focus",onFocus);return()=>{window.clearInterval(interval);window.removeEventListener("focus",onFocus)}},[refreshMarket]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelectedSticker(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  async function request(url:string,options:RequestInit={}){setBusy(true);try{const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success("Operação concluída.");location.reload();return data}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível concluir.")}finally{setBusy(false)}}
  async function buyPack(){
    if(!confirm("Comprar um Pacote Maker por 30 DC? Ele contém três figurinhas e pode trazer repetidas."))return;
    setBusy(true);
    try{
      const response=await fetch("/api/student/stickers/packs",{method:"POST"});
      const data=await response.json();
      if(!response.ok)throw new Error(data.message);
      setPackReveal(data.copies.map((copy:{sticker:PackSticker})=>copy.sticker));
    }catch(error){toast.error(error instanceof Error?error.message:"Não foi possível abrir o pacote.")}finally{setBusy(false)}
  }
  async function submitAction(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!action)return;const form=new FormData(event.currentTarget);const body=action.kind==="SELL"?{copyId:action.copyId,price:Number(form.get("price")),password:form.get("password")}:{copyId:action.copyId,recipientCode:form.get("recipientCode"),password:form.get("password")};await request(action.kind==="SELL"?"/api/student/stickers/listings":"/api/student/stickers/donations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})}
  return <div className="space-y-6">
    <section className="grid gap-4 sm:grid-cols-4"><Metric label="Patente" value={patent}/><Metric label="Score" value={String(score)}/><Metric label="Saldo" value={`${devCoins} DC`}/><Metric label="Pacotes hoje" value={`${remainingPacks} restantes`}/></section>
    {!marketOpen&&<section className="rounded-2xl border border-amber-400/25 bg-amber-400/8 p-5"><p className="font-bold text-amber-100">Compras e vendas estão desativadas</p><p className="mt-1 text-sm text-slate-300">O professor pausou o mercado entre alunos. Você ainda pode cancelar seus anúncios e usar os outros recursos do álbum.</p></section>}
    <section className="glass rounded-3xl p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="eyebrow">Pacote Maker</p><h2 className="mt-2 font-display text-2xl font-bold">3 figurinhas por 30 DC</h2><p className="mt-2 text-sm text-slate-400">Pode conter repetidas. Sem valor monetário e sem reembolso.</p><p className="mt-2 text-xs text-slate-500">Estoque: baixa {treasuryStock.LOW??0} · média {treasuryStock.MEDIUM??0} · alta {treasuryStock.HIGH??0}</p></div><button className="button-primary" onClick={buyPack} disabled={busy||remainingPacks<1||devCoins<30}><PackageOpen/>Abrir pacote</button></div></section>
    {donations.length>0&&<section className="rounded-2xl border border-violet-400/25 bg-violet-400/8 p-5"><h2 className="font-display text-xl font-bold">Doações aguardando você</h2><div className="mt-4 grid gap-3">{donations.map(d=><div key={d.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-slate-950/40 p-3"><Image src={d.copy.sticker.imagePath} alt={d.copy.sticker.alt} width={48} height={64} className="rounded"/><p className="mr-auto text-sm"><b>{d.copy.sticker.name}</b><br/><span className="text-slate-400">de {d.sender.firstName} · custa 20 XP para aceitar</span></p><button className="button-primary py-2" onClick={()=>request(`/api/student/stickers/donations/${d.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"ACCEPT"})})}>Aceitar</button><button className="button-secondary py-2" onClick={()=>request(`/api/student/stickers/donations/${d.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"DECLINE"})})}>Recusar</button></div>)}</div></section>}
    <section><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-4 text-slate-500" size={18}/><span className="sr-only">Buscar por nome</span><input className="input pl-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar figurinha"/></label><select className="input sm:max-w-52" aria-label="Filtrar por raridade" value={rarity} onChange={e=>setRarity(e.target.value)}><option value="ALL">Todas</option><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></select></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{filtered.map(sticker=>{const owned=sticker.copies.length;const free=sticker.copies.filter(c=>c.state==="OWNED");return <article key={sticker.id} className="glass overflow-hidden rounded-2xl"><button type="button" onClick={()=>setSelectedSticker(sticker)} aria-label={`Ver detalhes de ${sticker.name}`} className="focus-ring block w-full text-left"><span className="relative block aspect-[3/4] bg-slate-950"><Image src={sticker.imagePath} alt={sticker.alt} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 25vw, 16vw" className={`object-cover transition duration-300 hover:scale-[1.03] ${owned?"":"grayscale opacity-45"}`}/>{owned>0&&<span aria-label={`${owned} cópias possuídas`} className="absolute bottom-2 right-2 grid min-h-8 min-w-8 place-items-center rounded-full bg-blue-500 px-2 text-sm font-black">{owned}</span>}</span><span className="block p-3"><span className="block text-[11px] text-slate-500">#{sticker.number} · {rarityLabels[sticker.rarity]} · {sticker.score} pts</span><span className="mt-1 block font-bold">{sticker.name}</span><span className="mt-1 line-clamp-2 text-xs text-slate-400">{sticker.description}</span><span className="mt-2 block text-xs font-bold text-blue-300">Ver detalhes</span></span></button>{free.length>1&&<div className="flex gap-2 px-3 pb-3"><button className="button-secondary flex-1 px-2 py-2 text-xs" disabled={!marketOpen} title={marketOpen?undefined:"Compras e vendas desativadas pelo professor"} onClick={()=>setAction({kind:"SELL",copyId:free[1].id,rarity:sticker.rarity})}><Tag size={14}/>Vender</button><button className="button-secondary flex-1 px-2 py-2 text-xs" onClick={()=>setAction({kind:"DONATE",copyId:free[1].id})}><Gift size={14}/>Doar</button></div>}</article>})}</div></section>
    {ownListings.length>0&&<section className="glass rounded-2xl p-5"><h2 className="font-display text-xl font-bold">Meus anúncios</h2><div className="mt-4 grid gap-3">{ownListings.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 p-3 text-sm"><span><b>{item.copy.sticker.name}</b> · {item.price} DC</span><button className="button-secondary py-2" onClick={()=>confirm("Cancelar este anúncio e liberar a duplicata?")&&request(`/api/student/stickers/listings/${item.id}`,{method:"DELETE"})}>Cancelar</button></div>)}</div></section>}
    <section className="glass rounded-2xl p-5"><h2 className="font-display text-xl font-bold">Mercado global</h2><p className="mt-1 text-sm text-slate-400">{marketOpen?"Somente figurinhas de outros alunos que você ainda não possui.":"Mercado pausado pelo professor. Os anúncios permanecem visíveis, mas não podem ser comprados."}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{listings.length?listings.map(l=><div key={l.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><Image src={l.copy.sticker.imagePath} alt={l.copy.sticker.alt} width={54} height={72} className="rounded-md"/><div className="mr-auto"><p className="font-bold">{l.copy.sticker.name}</p><p className="text-xs text-slate-400">{l.seller.firstName} · {l.price} DC · {rarityLabels[l.copy.sticker.rarity]}</p></div><button className="button-primary px-3 py-2" disabled={busy||devCoins<l.price||!marketOpen} title={marketOpen?undefined:"Compras desativadas pelo professor"} onClick={()=>confirm(`Comprar por ${l.price} DC?`)&&request(`/api/student/stickers/listings/${l.id}/purchase`,{method:"POST"})}><ShoppingCart size={16}/>Comprar</button></div>):<p className="text-sm text-slate-500">{marketOpen?"Nenhum anúncio disponível para esta conta. Anúncios próprios e figurinhas que você já possui não aparecem aqui.":"Não é possível comprar enquanto o mercado estiver pausado."}</p>}</div></section>
    {selectedSticker&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/85 p-4 backdrop-blur-sm" onMouseDown={event=>event.target===event.currentTarget&&setSelectedSticker(null)}><section role="dialog" aria-modal="true" aria-labelledby="sticker-detail-title" className="glass relative grid w-full max-w-3xl gap-6 rounded-3xl p-5 sm:grid-cols-[minmax(220px,.75fr)_1fr] sm:p-7"><button type="button" onClick={()=>setSelectedSticker(null)} aria-label="Fechar detalhes" className="focus-ring absolute right-3 top-3 z-10 rounded-full bg-slate-950/80 p-2 text-slate-300 hover:text-white"><X/></button><div className="relative aspect-[3/4] overflow-hidden rounded-2xl bg-slate-950"><Image src={selectedSticker.imagePath} alt={selectedSticker.alt} fill sizes="(max-width: 640px) 90vw, 320px" className={`object-cover ${selectedSticker.copies.length?"":"grayscale opacity-60"}`}/></div><div className="self-center"><p className="eyebrow">{selectedSticker.collection.name}</p><h2 id="sticker-detail-title" className="mt-3 font-display text-3xl font-black">{selectedSticker.name}</h2><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full border border-slate-700 px-3 py-2">Número #{selectedSticker.number}</span><span className="rounded-full border border-slate-700 px-3 py-2">Raridade {rarityLabels[selectedSticker.rarity]}</span><span className="rounded-full border border-slate-700 px-3 py-2">{selectedSticker.score} pontos</span><span className="rounded-full border border-slate-700 px-3 py-2">{selectedSticker.copies.length} na sua coleção</span></div><h3 className="mt-6 text-sm font-bold uppercase tracking-wider text-slate-400">Descrição completa</h3><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-200">{selectedSticker.description}</p><p className="mt-5 text-xs text-slate-500">{selectedSticker.totalCopies} cópias emitidas no sistema.</p></div></section></div>}
    {packReveal&&<div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto bg-[#070b16]/95 p-4 backdrop-blur-xl"><section role="dialog" aria-modal="true" aria-labelledby="pack-reveal-title" className="relative w-full max-w-4xl overflow-hidden rounded-[2rem] border border-blue-300/25 bg-gradient-to-b from-blue-950 to-slate-950 p-6 text-center shadow-[0_0_100px_rgba(59,130,246,.25)] sm:p-10">{Array.from({length:18},(_,index)=><i key={index} aria-hidden="true" className="pack-spark" style={{left:`${5+(index*37)%90}%`,top:`${5+(index*53)%85}%`,animationDelay:`${(index%6)*.18}s`}}/>)}<Sparkles className="mx-auto text-amber-300" size={38} aria-hidden="true"/><p className="eyebrow mt-4">Pacote aberto</p><h2 id="pack-reveal-title" className="mt-3 font-display text-3xl font-black sm:text-4xl">Seu Pacote Maker chegou!</h2><p className="mt-2 text-sm text-slate-300">Estas três figurinhas agora fazem parte do seu álbum.</p><div className="relative mt-8 grid grid-cols-3 gap-2 sm:gap-5">{packReveal.map((sticker,index)=><article key={`${sticker.slug}-${index}`} className="sticker-reveal-card overflow-hidden rounded-xl border border-blue-300/25 bg-slate-900 text-left shadow-2xl sm:rounded-2xl" style={{animationDelay:`${index*.22}s`}}><div className="relative aspect-[3/4]"><Image src={sticker.imagePath} alt={sticker.name} fill sizes="(max-width: 640px) 30vw, 220px" className="object-cover"/></div><div className="p-2 sm:p-4"><p className="truncate text-xs font-black sm:text-base">{sticker.name}</p><p className="mt-1 text-[10px] text-slate-400 sm:text-xs">{rarityLabels[sticker.rarity]} · {sticker.score} pts</p></div></article>)}</div><button type="button" className="button-primary relative mt-8" onClick={()=>location.reload()}><Sparkles size={18}/>Guardar no álbum</button></section></div>}
    {action&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4" onMouseDown={event=>event.target===event.currentTarget&&setAction(null)}><form onSubmit={submitAction} role="dialog" aria-modal="true" aria-labelledby="sticker-action-title" className="glass w-full max-w-md rounded-2xl p-6"><h2 id="sticker-action-title" className="font-display text-xl font-bold">{action.kind==="SELL"?"Anunciar duplicata":"Doar duplicata"}</h2>{action.kind==="SELL"?<label className="mt-5 block text-sm">Preço em DC ({action.rarity==="HIGH"?"20–300":action.rarity==="MEDIUM"?"10–150":"5–60"})<input className="input mt-2" name="price" type="number" min={action.rarity==="HIGH"?20:action.rarity==="MEDIUM"?10:5} max={action.rarity==="HIGH"?300:action.rarity==="MEDIUM"?150:60} required autoFocus/></label>:<label className="mt-5 block text-sm">Código de acesso do colega<input className="input mt-2" name="recipientCode" required autoFocus/></label>}<label className="mt-4 block text-sm">Sua senha atual<input className="input mt-2" name="password" type="password" autoComplete="current-password" required/></label><div className="mt-5 flex gap-3"><button className="button-primary flex-1" disabled={busy}>Confirmar</button><button type="button" className="button-secondary" onClick={()=>setAction(null)}>Cancelar</button></div></form></div>}
  </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="glass rounded-2xl p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-display text-xl font-bold">{value}</p></div>}
