"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, ExternalLink } from "lucide-react";

type Question={id:string;prompt:string;type:"SINGLE_CHOICE"|"MULTIPLE_CHOICE"|"WRITTEN";maxXp:number;options:{id:string;text:string}[]};
export function ExternalActivityActions({activityId,url,signaled}:{activityId:string;url:string;signaled:boolean}){const router=useRouter();const[message,setMessage]=useState("");async function signal(){const response=await fetch(`/api/student/activities/${activityId}/signal`,{method:"POST"});const data=await response.json();setMessage(response.ok?"Aviso enviado ao professor. Isso não concede XP.":data.message);if(response.ok)router.refresh()}return <div className="mt-6 space-y-3"><a href={url} target="_blank" rel="noopener noreferrer" className="button-primary w-full sm:w-auto"><ExternalLink size={18}/>Abrir link</a><div><button disabled={signaled} onClick={signal} className="button-secondary w-full sm:w-auto"><CheckCircle2 size={18}/>{signaled?"Marcada como realizada":"Marcar como realizada"}</button></div><p className="text-xs text-slate-400">Abrir ou marcar como realizada apenas avisa o professor. O XP só é concedido depois da conferência.</p>{message&&<p role="status" className="text-sm text-blue-200">{message}</p>}</div>}

export function FormSubmission({activityId,questions}:{activityId:string;questions:Question[]}){const router=useRouter();const[answers,setAnswers]=useState<Record<string,{selectedOptionIds:string[];writtenText:string}>>(()=>Object.fromEntries(questions.map(question=>[question.id,{selectedOptionIds:[],writtenText:""}])));const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);function choose(question:Question,optionId:string){setAnswers(current=>{const selected=current[question.id].selectedOptionIds;return{...current,[question.id]:{...current[question.id],selectedOptionIds:question.type==="SINGLE_CHOICE"?[optionId]:selected.includes(optionId)?selected.filter(id=>id!==optionId):[...selected,optionId]}}})}async function submit(event:React.FormEvent){event.preventDefault();if(!confirm("Enviar o formulário? O envio é único e não poderá ser alterado."))return;setBusy(true);const response=await fetch(`/api/student/activities/${activityId}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers:Object.entries(answers).map(([questionId,answer])=>({questionId,...answer}))})});const data=await response.json();setMessage(response.ok?"Formulário enviado com sucesso.":data.message);if(response.ok)router.refresh();setBusy(false)}return <form onSubmit={submit} className="mt-6 space-y-4">{questions.map((question,index)=><fieldset key={question.id} className="glass rounded-2xl p-5"><legend className="px-2 font-bold">{index+1}. {question.prompt}</legend><p className="mb-4 text-xs text-slate-500">Vale {question.maxXp} XP{question.type==="MULTIPLE_CHOICE"?" · somente o conjunto exato pontua":""}</p>{question.type==="WRITTEN"?<textarea required rows={5} value={answers[question.id].writtenText} onChange={event=>setAnswers(current=>({...current,[question.id]:{...current[question.id],writtenText:event.target.value}}))} className="input resize-y" placeholder="Escreva sua resposta"/>:<div className="space-y-2">{question.options.map(option=><label key={option.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-slate-700 bg-slate-950/25 p-3"><input required={question.type==="SINGLE_CHOICE"} type={question.type==="SINGLE_CHOICE"?"radio":"checkbox"} name={question.id} checked={answers[question.id].selectedOptionIds.includes(option.id)} onChange={()=>choose(question,option.id)}/><span>{option.text}</span></label>)}</div>}</fieldset>)}<button disabled={busy} className="button-primary w-full sm:w-auto">{busy?"Enviando…":"Enviar respostas"}</button>{message&&<p role="status" className="text-sm text-slate-300">{message}</p>}</form>}
