"use client";
import { useMemo, useState } from "react";
import { Archive, KeyRound, Pencil, Plus, RotateCcwKey, Search, UsersRound, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { EmptyState } from "./empty-state";

export type StudentRow = { id:string; firstName:string; lastName:string; accessCode:string; schoolClass:string|null; status:"ACTIVE"|"INACTIVE"; xp:number; mustChangePassword:boolean; createdAt:string; updatedAt:string; lastLoginAt:string|null; lastSeenAt:string|null };
const classes=["GRADE_6_A","GRADE_6_B","GRADE_6_C","GRADE_7_A","GRADE_7_B","GRADE_7_C"] as const;
const labels:Record<string,string>={GRADE_6_A:"6º Ano A",GRADE_6_B:"6º Ano B",GRADE_6_C:"6º Ano C",GRADE_7_A:"7º Ano A",GRADE_7_B:"7º Ano B",GRADE_7_C:"7º Ano C"};
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Nunca";
const ONLINE_REFERENCE = Date.now();

export function StudentManager({initialStudents}:{initialStudents:StudentRow[]}) {
  const router=useRouter(); const [students,setStudents]=useState(initialStudents); const [query,setQuery]=useState(""); const [filter,setFilter]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [modal,setModal]=useState<"create"|"edit"|"xp"|"archive"|null>(null); const [editing,setEditing]=useState<StudentRow|null>(null); const [busy,setBusy]=useState(false);
  const visible=useMemo(()=>students.filter(s=>(!filter||s.schoolClass===filter)&&`${s.firstName} ${s.lastName}`.toLowerCase().includes(query.toLowerCase())),[students,query,filter]);
  async function request(url:string,options:RequestInit){setBusy(true);const response=await fetch(url,options);const data=await response.json();setBusy(false);if(!response.ok){toast.error(data.message);throw new Error(data.message)}return data}
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await request("/api/professor/students",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setStudents(v=>[data.student,...v]);setModal(null);toast.success(`Aluno criado. Código: ${data.student.accessCode}`);router.refresh()}catch{}}
  async function edit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);try{await request(`/api/professor/students/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const next={...editing,firstName:String(f.get("firstName")),lastName:String(f.get("lastName")),schoolClass:String(f.get("schoolClass")),updatedAt:new Date().toISOString()};setStudents(v=>v.map(s=>s.id===editing.id?next:s));setEditing(next);toast.success("Aluno atualizado.")}catch{}}
  async function resetPassword(){if(!editing||!confirm(`Redefinir a senha de ${editing.firstName} para 12345678? As sessões abertas serão encerradas.`))return;try{await request(`/api/professor/students/${editing.id}/reset-password`,{method:"POST"});const next={...editing,mustChangePassword:true};setEditing(next);setStudents(v=>v.map(s=>s.id===editing.id?next:s));toast.success("Senha redefinida. A troca será exigida no próximo acesso.")}catch{}}
  async function bulk(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const action=modal==="xp"?"XP":"ARCHIVE";const body:Record<string,unknown>={action,ids:selected,adminPassword:f.get("adminPassword")};if(action==="XP"){body.amount=Number(f.get("amount"));body.reason=f.get("reason")}try{const data=await request("/api/professor/students/bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setStudents(v=>v.map(s=>selected.includes(s.id)?action==="XP"?{...s,xp:s.xp+Number(body.amount)}:{...s,status:"INACTIVE"}:s));setSelected([]);setModal(null);toast.success(`${data.updated} aluno(s) atualizado(s).`)}catch{}}
  const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  return <section className="glass mt-7 overflow-hidden rounded-2xl">
    <div className="flex flex-col justify-between gap-4 border-b border-slate-700 p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="eyebrow">Gestão da turma</p><h2 className="mt-2 font-display text-xl font-bold">Alunos da Sala Maker</h2><p className="mt-1 text-xs text-slate-400">Uma turma de Robótica, organizada pela turma escolar de origem.</p></div><div className="flex flex-wrap gap-2"><button disabled={!selected.length} onClick={()=>setModal("xp")} className="button-secondary text-sm disabled:opacity-40"><Zap size={16}/>Adicionar XP ({selected.length})</button><button disabled={!selected.length} onClick={()=>setModal("archive")} className="button-secondary text-sm text-rose-200 disabled:opacity-40"><Archive size={16}/>Arquivar</button><button onClick={()=>{setEditing(null);setModal("create")}} className="button-primary text-sm"><Plus size={16}/>Adicionar aluno</button></div></div>
    <div className="flex flex-col gap-3 p-5 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 z-10 -translate-y-1/2 text-slate-500" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="input py-2.5" style={{paddingLeft:"3rem"}} placeholder="Buscar aluno pelo nome..."/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="input sm:max-w-56"><option value="">Todas as turmas escolares</option>{classes.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></div>
    <div className="px-5 pb-5">{visible.length?<div className="overflow-x-auto rounded-xl border border-slate-700"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-900/70 text-xs uppercase text-slate-400"><tr><th className="p-4"><input type="checkbox" checked={visible.every(s=>selected.includes(s.id))} onChange={e=>setSelected(e.target.checked?Array.from(new Set([...selected,...visible.map(s=>s.id)])):selected.filter(id=>!visible.some(s=>s.id===id)))}/></th><th>Aluno</th><th>Turma</th><th>XP</th><th>Status</th><th>Código</th><th className="pr-4 text-right">Ações</th></tr></thead><tbody className="divide-y divide-slate-800">{visible.map(s=><tr key={s.id}><td className="p-4"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/></td><td><strong>{s.firstName} {s.lastName}</strong></td><td>{s.schoolClass?labels[s.schoolClass]:"—"}</td><td className="font-bold text-blue-300">{s.xp} XP</td><td>{s.status==="ACTIVE"?"Ativo":"Arquivado"}</td><td className="font-mono text-xs text-slate-400">{s.accessCode}</td><td className="pr-4 text-right"><button onClick={()=>{setEditing(s);setModal("edit")}} className="rounded-lg p-2 text-slate-400 hover:text-blue-200" aria-label={`Editar ${s.firstName}`}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>:<EmptyState icon={UsersRound} title="Nenhum aluno encontrado" description="Adicione o primeiro aluno ou ajuste os filtros."/>}</div>
    {modal&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/80 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className={`glass my-6 w-full rounded-2xl p-6 ${modal==="edit"?"max-w-2xl":"max-w-md"}`}><div className="flex items-center justify-between"><h3 className="font-display text-xl font-bold">{{create:"Adicionar aluno",edit:"Ficha do aluno",xp:"Adicionar XP",archive:"Arquivar alunos"}[modal]}</h3><button onClick={()=>setModal(null)}><X/></button></div>
      {modal==="create"&&<StudentForm onSubmit={create} busy={busy}/>} {modal==="edit"&&editing&&<form onSubmit={edit} className="mt-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><input name="firstName" defaultValue={editing.firstName} className="input" required/></Field><Field label="Sobrenome"><input name="lastName" defaultValue={editing.lastName} className="input" required/></Field><Field label="Turma escolar"><select name="schoolClass" defaultValue={editing.schoolClass??""} className="input" required>{classes.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></Field><Read label="Código de acesso" value={editing.accessCode}/><Read label="XP atual" value={`${editing.xp} XP`}/><Read label="Status" value={editing.status==="ACTIVE"?"Ativo":"Arquivado"}/><Read label="Criado em" value={fmt(editing.createdAt)}/><Read label="Atualizado em" value={fmt(editing.updatedAt)}/><Read label="Último login" value={fmt(editing.lastLoginAt)}/><Read label="Última atividade" value={fmt(editing.lastSeenAt)}/><Read label="Estado agora" value={editing.lastSeenAt&&ONLINE_REFERENCE-new Date(editing.lastSeenAt).getTime()<300000?"Online":"Offline"}/><Read label="Senha" value={editing.mustChangePassword?"Troca obrigatória pendente":"Senha definida pelo aluno"}/></div><div className="mt-6 flex flex-col gap-3 border-t border-slate-700 pt-5 sm:flex-row"><button disabled={busy} className="button-primary flex-1">Salvar alterações</button><button type="button" disabled={busy} onClick={resetPassword} className="button-secondary flex-1"><RotateCcwKey size={17}/>Redefinir senha</button></div><p className="mt-3 text-xs text-slate-500">Código, XP, status e datas são somente leitura. XP e arquivamento possuem fluxos próprios.</p></form>}
      {(modal==="xp"||modal==="archive")&&<form onSubmit={bulk} className="mt-6 space-y-4"><p className="text-sm text-slate-400">Ação em <strong className="text-white">{selected.length} aluno(s)</strong>.</p>{modal==="xp"&&<><input name="amount" type="number" min="1" max="10000" className="input" placeholder="Quantidade de XP" required/><input name="reason" className="input" placeholder="Motivo" required/></>}<Field label="Senha administrativa"><div className="relative"><KeyRound className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input name="adminPassword" type="password" className="input" style={{paddingLeft:"3rem"}} required/></div></Field><button disabled={busy} className={modal==="archive"?"w-full rounded-xl bg-rose-500 px-4 py-3 font-bold":"button-primary w-full"}>{busy?"Processando...":modal==="archive"?"Confirmar arquivamento":"Adicionar XP"}</button></form>}
    </div></div>}
  </section>
}
function StudentForm({onSubmit,busy}:{onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <form onSubmit={onSubmit} className="mt-6 space-y-4"><input name="firstName" className="input" placeholder="Nome" required/><input name="lastName" className="input" placeholder="Sobrenome" required/><select name="schoolClass" className="input" required><option value="">Turma escolar</option>{classes.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select><p className="rounded-xl bg-amber-300/10 p-3 text-xs text-amber-100">Senha inicial: <strong>12345678</strong>. A troca será obrigatória.</p><button disabled={busy} className="button-primary w-full">{busy?"Salvando...":"Criar aluno"}</button></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold"><span className="mb-2 block">{label}</span>{children}</label>}
function Read({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-700 bg-slate-950/35 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div>}
