-- A Sala Maker possui uma única turma de Robótica. A turma escolar é somente
-- uma informação de origem do aluno e não define o público de aulas/atividades.

DROP INDEX IF EXISTS "User_schoolClass_status_idx";
ALTER TABLE "User" RENAME COLUMN "schoolClass" TO "originSchoolClass";
CREATE INDEX "User_originSchoolClass_status_idx" ON "User"("originSchoolClass", "status");

CREATE TABLE "LessonParticipant" (
  "id" UUID NOT NULL,
  "lessonId" UUID NOT NULL,
  "studentId" UUID NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "LessonParticipant_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "LessonParticipant_lessonId_studentId_key" ON "LessonParticipant"("lessonId", "studentId");
CREATE INDEX "LessonParticipant_studentId_lessonId_idx" ON "LessonParticipant"("studentId", "lessonId");
ALTER TABLE "LessonParticipant" ADD CONSTRAINT "LessonParticipant_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LessonParticipant" ADD CONSTRAINT "LessonParticipant_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Preserve historical eligibility wherever attendance already proves that the
-- student belonged to the lesson. UUIDs are generated by PostgreSQL.
INSERT INTO "LessonParticipant" ("id", "lessonId", "studentId")
SELECT gen_random_uuid(), "lessonId", "studentId" FROM "Attendance"
ON CONFLICT ("lessonId", "studentId") DO NOTHING;

-- Any lesson still open at deployment becomes a lesson for the whole active
-- Robótica cohort, which is the corrected product rule.
INSERT INTO "LessonParticipant" ("id", "lessonId", "studentId")
SELECT gen_random_uuid(), lesson."id", student."id"
FROM "Lesson" lesson
CROSS JOIN "User" student
WHERE lesson."status" = 'OPEN' AND student."role" = 'STUDENT' AND student."status" = 'ACTIVE'
ON CONFLICT ("lessonId", "studentId") DO NOTHING;

DROP INDEX IF EXISTS "Lesson_schoolClass_status_idx";
ALTER TABLE "Lesson" DROP COLUMN "schoolClass";

DROP INDEX IF EXISTS "Activity_schoolClass_opensAt_closesAt_idx";
ALTER TABLE "Activity" DROP COLUMN "schoolClass";
CREATE INDEX "Activity_opensAt_closesAt_idx" ON "Activity"("opensAt", "closesAt");
