import Link from "next/link";
import { CalendarDays, History, Trophy, UserRound, Zap } from "lucide-react";
import { BehaviorChart } from "@/components/behavior-chart";
import { Brand } from "@/components/brand";
import { LogoutButton } from "@/components/logout-button";
import { EmptyState } from "@/components/empty-state";
import { requireStudent } from "@/lib/authorization";
import { prisma } from "@/lib/db";

const labels:Record<string,string>={GRADE_6_A:"6º Ano A",GRADE_6_B:"6º Ano B",GRADE_6_C:"6º Ano C",GRADE_7_A:"7º Ano A",GRADE_7_B:"7º Ano B",GRADE_7_C:"7º Ano C"};
export default async function Aluno(){
  const{student}=await requireStudent();
  const[ranking,closedLessons,presentCount,history,behaviors]=await Promise.all([
    prisma.user.findMany({where:{role:"STUDENT",status:"ACTIVE"},select:{id:true},orderBy:[{xp:"desc"},{createdAt:"asc"},{id:"asc"}]}),
    prisma.lesson.count({where:{status:"CLOSED",participants:{some:{studentId:student.id}}}}),
    prisma.attendance.count({where:{studentId:student.id,status:"PRESENT",lesson:{status:"CLOSED",participants:{some:{studentId:student.id}}}}}),
    prisma.xpEntry.findMany({where:{studentId:student.id},select:{id:true,delta:true,reason:true,createdAt:true},orderBy:{createdAt:"desc"},take:6}),
    prisma.behaviorRating.findMany({where:{studentId:student.id},select:{id:true,score:true,reason:true,createdAt:true,lesson:{select:{title:true}}},orderBy:{createdAt:"desc"},take:8}),
  ]);
  const position=ranking.findIndex(item=>item.id===student.id)+1;const frequency=closedLessons?Math.round(presentCount/closedLessons*100):0;
  return <main className="mesh mobile-safe min-h-screen"><div className="mx-auto max-w-6xl px-5 sm:px-8"><header className="flex h-20 items-center justify-between border-b border-white/7"><Brand context="Estudante"/><div className="flex items-center gap-2"><Link href="/ranking" className="button-secondary py-2 text-sm"><Trophy size={16}/>Ranking</Link><LogoutButton/></div></header><section className="mt-8 overflow-hidden rounded-3xl border border-blue-400/20 bg-gradient-to-br from-[#142b4d] to-[#101d30] p-6 sm:p-9"><p className="eyebrow">Minha jornada na Robótica</p><h1 className="mt-3 font-display text-3xl font-bold">Olá, {student.firstName}! <span className="text-blue-300">Vamos criar?</span></h1><p className="mt-2 text-sm text-slate-400">Turma de Robótica · origem: {student.originSchoolClass?labels[student.originSchoolClass]:"não informada"} · Código {student.accessCode}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric icon={Zap} label="XP atual" value={`${student.xp} XP`}/><Metric icon={Trophy} label="Posição" value={position?`${position}º lugar`:"—"}/><Metric icon={CalendarDays} label="Frequência" value={`${frequency}%`}/></div></section><Link href="/aluno/atividades" className="button-primary mt-5 w-full sm:w-auto">Ver minhas atividades</Link><div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="glass rounded-2xl p-5"><h2 className="flex items-center gap-2 font-display text-xl font-bold"><UserRound size={20}/>Minha conta</h2><dl className="mt-5 space-y-4 text-sm"><Info label="Nome" value={`${student.firstName} ${student.lastName}`}/><Info label="Turma regular de origem" value={student.originSchoolClass?labels[student.originSchoolClass]:"Não informada"}/><Info label="Último login" value={student.lastLoginAt?student.lastLoginAt.toLocaleString("pt-BR"):"Primeiro acesso"}/><Info label="Status na Robótica" value="Ativo"/></dl><p className="mt-5 text-xs text-slate-500">A sessão do aluno encerra automaticamente 30 minutos após o login.</p></section><section className="glass rounded-2xl p-5"><h2 className="font-display text-xl font-bold">Histórico recente de XP</h2>{history.length?<div className="mt-4 divide-y divide-slate-800">{history.map(item=><div key={item.id} className="flex gap-4 py-4"><span className={`font-bold ${item.delta>=0?"text-emerald-300":"text-rose-300"}`}>{item.delta>=0?"+":""}{item.delta} XP</span><div><p className="text-sm">{item.reason}</p><p className="text-xs text-slate-500">{item.createdAt.toLocaleString("pt-BR")}</p></div></div>)}</div>:<div className="mt-4"><EmptyState icon={History} title="Sem movimentações" description="Presença e outras alterações de XP aparecerão aqui."/></div>}</section></div><BehaviorChart ratings={behaviors}/></div></main>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Zap;label:string;value:string}){return <div className="rounded-2xl border border-blue-300/15 bg-blue-300/7 p-4"><Icon className="text-blue-300" size={19}/><p className="mt-4 text-xs text-slate-400">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
